help:
	@echo

frontend:
	@sh Components/frontend.sh

mongodb:
	@sh Components/mongodb.sh

catalogue:
	@sh Components/catalogue.sh

redis:
	@sh Components/redis.sh

user:
	@sh Components/user.sh

cart:
	@sh Components/cart.sh

mysql:
	@sh Components/mysql.sh

shipping:
	@sh Components/shipping.sh

payment:
	@sh Components/payment.sh

rabbitmq:
	@sh Components/rabbitmq.sh
